/**
 * generated by Xtext
 */
package org.fuin.xsample.ui.contentassist;

import org.fuin.xsample.ui.contentassist.AbstractXSampleDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class XSampleDslProposalProvider extends AbstractXSampleDslProposalProvider {
}
