/*
 * generated by Xtext
 */
package org.fuin.xsample;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XSampleDslRuntimeModule extends org.fuin.xsample.AbstractXSampleDslRuntimeModule {

}
