/*
* generated by Xtext
*/
package org.fuin.xsample;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XSampleDslStandaloneSetup extends XSampleDslStandaloneSetupGenerated{

	public static void doSetup() {
		new XSampleDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

