/*
 * generated by Xtext
 */
package org.fuin.xsample.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XSampleDslUiModule extends org.fuin.xsample.ui.AbstractXSampleDslUiModule {
	public XSampleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
