/*
 * generated by Xtext
 */
package org.fuin.xsample.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.fuin.xsample.ui.internal.XSampleDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XSampleDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XSampleDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XSampleDslActivator.getInstance().getInjector(XSampleDslActivator.ORG_FUIN_XSAMPLE_XSAMPLEDSL);
	}
	
}
