/*
* generated by Xtext
*/
package org.fuin.xsample.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XSampleDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/fuin/xsample/parser/antlr/internal/InternalXSampleDsl.tokens");
	}
}
