/*
* generated by Xtext
*/
package org.fuin.xsample.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.fuin.xsample.services.XSampleDslGrammarAccess;

public class XSampleDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XSampleDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.fuin.xsample.parser.antlr.internal.InternalXSampleDslParser createParser(XtextTokenStream stream) {
		return new org.fuin.xsample.parser.antlr.internal.InternalXSampleDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public XSampleDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XSampleDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
