/**
 * generated by Xtext
 */
package org.fuin.xsample.validation;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XSampleDslValidator extends AbstractXSampleDslValidator {
}
